---
- name: Update sources.list
  template:
    src: etc/apt/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Upgrade packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400
- name: Install packages
  apt:
    name: "{{ item }}"
  loop:
    - bash-completion
    - build-essential
    - btrfs-tools
    - cmake
    - curl
    - dnsutils
    - htop
    - iotop
    - isc-dhcp-client
    - iputils-ping
    - kmod
    - linux-firmware
    - locales
    - net-tools
    - netplan.io
    - pciutils
    - python3-dev
    - ssh
    - sudo
    - systemd
    - udev
    - unzip
    - usbutils
    - vim
    - wpasupplicant

- name: Generate locales
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Enable services
  shell: systemctl enable {{ item }}
  loop:
    - ssh
    - systemd-networkd
    - systemd-resolved

- name: Create network conf
  template:
    src: etc/netplan/netcfg.yaml
    dest: /etc/netplan/netcfg.yaml
    owner: root
    group: root
    mode: 0644

- name: Create new user
  user:
    name: "{{ new_user.name }}"
    shell: "{{ new_user.shell }}"
    password: "{{ new_user.password | password_hash('sha512') }}"
    create_home: yes
    groups: sudo
    state: present

- name: Download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Install pip
  shell: python3 /tmp/get-pip.py --user
  become: yes
  become_user: "{{ new_user.name }}"
